/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppErrorDevSection: typeof import('./src/components/app-error/AppErrorDevSection.vue')['default']
    AppErrorPage: typeof import('./src/components/app-error/AppErrorPage.vue')['default']
    AppErrorProdSection: typeof import('./src/components/app-error/AppErrorProdSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
